/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a LocalTime.
 */
class LocalTime {
  /**
   * Create a LocalTime.
   * @property {number} [hour]
   * @property {number} [minute]
   * @property {number} [second]
   * @property {number} [nano]
   */
  constructor() {
  }

  /**
   * Defines the metadata of LocalTime
   *
   * @returns {object} metadata of LocalTime
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'LocalTime',
      type: {
        name: 'Composite',
        className: 'LocalTime',
        modelProperties: {
          hour: {
            required: false,
            serializedName: 'hour',
            type: {
              name: 'Number'
            }
          },
          minute: {
            required: false,
            serializedName: 'minute',
            type: {
              name: 'Number'
            }
          },
          second: {
            required: false,
            serializedName: 'second',
            type: {
              name: 'Number'
            }
          },
          nano: {
            required: false,
            serializedName: 'nano',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = LocalTime;
