/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a LRAInfo.
 */
class LRAInfo {
  /**
   * Create a LRAInfo.
   * @property {number} [timeNow]
   * @property {string} [lraId]
   * @property {boolean} [compensated]
   * @property {boolean} [recovering]
   * @property {number} [finishTime]
   * @property {boolean} [complete]
   * @property {boolean} [topLevel]
   * @property {object} [zoneOffset]
   * @property {number} [zoneOffset.totalSeconds]
   * @property {string} [zoneOffset.id]
   * @property {object} [zoneOffset.rules]
   * @property {boolean} [zoneOffset.rules.fixedOffset]
   * @property {array} [zoneOffset.rules.transitions]
   * @property {array} [zoneOffset.rules.transitionRules]
   * @property {number} [startTime]
   * @property {string} [clientId]
   * @property {boolean} [active]
   * @property {string} [status]
   */
  constructor() {
  }

  /**
   * Defines the metadata of LRAInfo
   *
   * @returns {object} metadata of LRAInfo
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'LRAInfo',
      type: {
        name: 'Composite',
        className: 'LRAInfo',
        modelProperties: {
          timeNow: {
            required: false,
            serializedName: 'timeNow',
            type: {
              name: 'Number'
            }
          },
          lraId: {
            required: false,
            serializedName: 'lraId',
            type: {
              name: 'String'
            }
          },
          compensated: {
            required: false,
            serializedName: 'compensated',
            type: {
              name: 'Boolean'
            }
          },
          recovering: {
            required: false,
            serializedName: 'recovering',
            type: {
              name: 'Boolean'
            }
          },
          finishTime: {
            required: false,
            serializedName: 'finishTime',
            type: {
              name: 'Number'
            }
          },
          complete: {
            required: false,
            serializedName: 'complete',
            type: {
              name: 'Boolean'
            }
          },
          topLevel: {
            required: false,
            serializedName: 'topLevel',
            type: {
              name: 'Boolean'
            }
          },
          zoneOffset: {
            required: false,
            serializedName: 'zoneOffset',
            type: {
              name: 'Composite',
              className: 'ZoneOffset'
            }
          },
          startTime: {
            required: false,
            serializedName: 'startTime',
            type: {
              name: 'Number'
            }
          },
          clientId: {
            required: false,
            serializedName: 'clientId',
            type: {
              name: 'String'
            }
          },
          active: {
            required: false,
            serializedName: 'active',
            type: {
              name: 'Boolean'
            }
          },
          status: {
            required: false,
            serializedName: 'status',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = LRAInfo;
