/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a TemporalUnit.
 */
class TemporalUnit {
  /**
   * Create a TemporalUnit.
   * @property {object} [duration]
   * @property {number} [duration.seconds]
   * @property {boolean} [duration.zero]
   * @property {array} [duration.units]
   * @property {boolean} [duration.negative]
   * @property {number} [duration.nano]
   * @property {boolean} [timeBased]
   * @property {boolean} [dateBased]
   * @property {boolean} [durationEstimated]
   */
  constructor() {
  }

  /**
   * Defines the metadata of TemporalUnit
   *
   * @returns {object} metadata of TemporalUnit
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TemporalUnit',
      type: {
        name: 'Composite',
        className: 'TemporalUnit',
        modelProperties: {
          duration: {
            required: false,
            serializedName: 'duration',
            type: {
              name: 'Composite',
              className: 'Duration'
            }
          },
          timeBased: {
            required: false,
            serializedName: 'timeBased',
            type: {
              name: 'Boolean'
            }
          },
          dateBased: {
            required: false,
            serializedName: 'dateBased',
            type: {
              name: 'Boolean'
            }
          },
          durationEstimated: {
            required: false,
            serializedName: 'durationEstimated',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = TemporalUnit;
