/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a ZoneOffset.
 */
class ZoneOffset {
  /**
   * Create a ZoneOffset.
   * @property {number} [totalSeconds]
   * @property {string} [id]
   * @property {object} [rules]
   * @property {boolean} [rules.fixedOffset]
   * @property {array} [rules.transitions]
   * @property {array} [rules.transitionRules]
   */
  constructor() {
  }

  /**
   * Defines the metadata of ZoneOffset
   *
   * @returns {object} metadata of ZoneOffset
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ZoneOffset',
      type: {
        name: 'Composite',
        className: 'ZoneOffset',
        modelProperties: {
          totalSeconds: {
            required: false,
            serializedName: 'totalSeconds',
            type: {
              name: 'Number'
            }
          },
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          rules: {
            required: false,
            serializedName: 'rules',
            type: {
              name: 'Composite',
              className: 'ZoneRules'
            }
          }
        }
      }
    };
  }
}

module.exports = ZoneOffset;
